qSLDcalc: LangAction Class Reference
LangAction Class Reference
QAction for language switching purposes.
#include <mainwindow.h>
Public Slots
void triggeredSlot ()
Emits a signal with the language filename as parameter.
Signals
void triggered (const QString &)
Same signal as QAction::triggered() but with the language filename as parameter.
Public Member Functions
LangAction (QObject *parent, const QString &fn)
Constructor.
Private Attributes
const QString langFilename
Language translation filename.
Detailed Description
QAction for language switching purposes.
Represents a menu entry for a certain language and knows about the translation filename for this language. If a language is loaded, the filename is translated into the name of the language. Otherwise, the plain filename is displayed in a menu, for example.
Definition at line 354 of file mainwindow.h.
Constructor & Destructor Documentation
LangAction::LangAction (QObject * parent, const QString & fn) [inline]
Constructor.
Parameters:
parent Parent QObject (usually Qt widget).
fn Filename of the language translation file.
Definition at line 363 of file mainwindow.h.
References triggered(), and triggeredSlot().
Member Function Documentation
void LangAction::triggered (const QString &) [signal]
Same signal as QAction::triggered() but with the language filename as parameter.
Referenced by LangAction(), and triggeredSlot().
void LangAction::triggeredSlot () [inline, slot]
Emits a signal with the language filename as parameter.
See also:
triggered(const QString&)
Definition at line 372 of file mainwindow.h.
References langFilename, and triggered().
Referenced by LangAction().
Field Documentation
const QString LangAction::langFilename [private]
Language translation filename.
Definition at line 378 of file mainwindow.h.
Referenced by triggeredSlot().
The documentation for this class was generated from the following file:
mainwindow.h