qSLDcalc: Element Class Reference
Element Class Reference
A real-world chemical element.
#include <element.h>
Public Types
enum Property {
SYMBOL_PROPERTY, NAME_PROPERTY, NUCLEONS_PROPERTY, ELECTRONS_PROPERTY,
ATOMIC_MASS_PROPERTY, ABUNDANCE_PROPERTY, NS_L_COHERENT_PROPERTY, NS_L_INCOHERENT_PROPERTY,
NS_CS_COHERENT_PROPERTY, NS_CS_INCOHERENT_PROPERTY, NS_CS_TOTAL_PROPERTY, NS_CS_ABSORPTION_PROPERTY,
XRAY_ENERGY_PROPERTY, INVALID_PROPERTY
}
All properties of an Element in the database.
enum PropertyType {
INT_TYPE, STRING_TYPE, DOUBLE_TYPE, COMPLEX_TYPE,
INVALID_TYPE
}
The data type of a property to allow for convenient testing at runtime.
typedef QPointer< Element > Ptr
A guarded Pointer to such an Element.
typedef boost::variant< int,
std::string, double, complex > PropertyVariant
Data type of a single property value.
typedef std::vector< Property > PropertyVector
Container for all defined properties.
typedef std::vector
< PropertyVariant > PropertyVariantVector
Container for all defined property values, the data.
typedef
PropertyVariantVector::const_iterator PropertyValueIteratorConst
typedef
PropertyVariantVector::iterator PropertyValueIterator
Public Member Functions
Element ()
Initializes all properties of this Element.
~Element ()
Releases all memory.
PropertyValueIteratorConst beginConst () const
Returns a read-only iterator to the first of all property values.
PropertyValueIteratorConst endConst () const
Returns a read-only iterator which points behind the last property value.
Property getProperty (const PropertyValueIteratorConst &iter) const
Returns the Property of the specified property value iterator created with beginConst() or endConst();.
const PropertyVariant & propertyConst (Property p) const
Returns the property value associated with the specified property.
template<typename T >
bool setProperty (Property p, const T &value)
Sets the specified property to the provided value.
double electrons () const
Provided for convenience.
double atomicMass () const
Provided for convenience.
complex nslCoherent () const
Provided for convenience.
complex nslIncoherent () const
Provided for convenience.
bool isValid () const
Tests this element for (physical) valid property values.
const MapTriple & xrayCoefficients () const
Provides read-only access to the X-Ray scattering factors.
void addXrayCoefficient (double energy, double fp, double fpp)
Adds a new triple to the X-Ray scattering factors.
Static Public Member Functions
static int propertyCount ()
Returns the overall number of available properties.
static Property getProperty (int index)
Returns the Property with the specified index.
static bool isValidVariant (const PropertyVariant &var)
Tests a given property value for invalid type.
static const char * propertyName (Property p)
Returns the name of a given property.
static PropertyType propertyType (Property p)
Returns the data type of a given property.
static bool isValidType (Property p, const PropertyVariant &var)
Tests if the given property value matches the given property.
Static Public Attributes
static const int INVALID_PROPERTY_VALUE = -2
Default value for properties with invalid type.
Private Member Functions
PropertyValueIterator begin ()
Returns a read/write iterator to the first of all property values.
PropertyValueIterator end ()
Returns a read/write iterator which points behind the last property value.
Property getProperty (const PropertyValueIterator &iter) const
Returns the Property of the specified property value iterator created with begin() or end();.
template<typename T >
T getValue (Property p) const
Returns the value of given property p.
virtual std::string doSymbol () const
Implementation of data access for cfp::ChemicalElementInterface.
virtual void doSetSymbol (const std::string &s)
Implementation of data access for cfp::ChemicalElementInterface.
virtual int doNucleons () const
Implementation of data access for cfp::ChemicalElementInterface.
virtual void doSetNucleons (int n)
Implementation of data access for cfp::ChemicalElementInterface.
Static Private Member Functions
static int defaultValue (int a, Element::Property p)
Explicitly typified default value for property p.
static double defaultValue (double a, Element::Property p)
Explicitly typified default value for property p.
static complex defaultValue (complex a, Element::Property p)
Explicitly typified default value for property p.
static std::string defaultValue (std::string a, Element::Property p)
Explicitly typified default value for property p.
Private Attributes
PropertyVariantVector mProperties
Container for all property values.
MapTriple mXrayCoefficients
Container for X-Ray scattering factors.
Static Private Attributes
static const char * mPropertyNames [INVALID_PROPERTY]
Points to the names of all properties.
Detailed Description
A real-world chemical element.
It is used to store all relevant characteristics and provide dynamic, i.e. automated, access to them. It is compatible to cfp::ChemicalElement but stores its data in a different manner: a container of variants (PropertyVariant). boost::variant is used to accomplish this.
Data sources:
For neutron scattering length and cross sections, the data is taken from http://www.ncnr.nist.gov/resources/n-lengths/list.html which references the Special Feature section of neutron scattering lengths and cross sections of the elements and their isotopes in Neutron News, Vol. 3, No. 3, 1992, pp. 29-37.
For X-Ray scattering factors, data is taken from http://skuld.bmsc.washington.edu/scatter/AS_periodic.html Which states: The scattering factor data files indexed through the table above were calculated using the subroutine library by Brennan and Cowan [...]. The values for f' and f" are derived using the theoretical approximation developed by Cromer and Liberman. This theory gives accurate values far from an absorption edge but does not account for the effects of neighboring atoms, which can be very substantial near an absorption edge. Before conducting an anomalous scattering experiment close to an absorption edge it is therefore advisable to determine the actual scattering behaviour of your sample [...].
Todo:
An alternative for internal value handling is QVariant. Possible advantage: More convenient use, especially regarding value retrieval. The visitor concept of boost::variant requires to introduce funtional objects for accessing or modifying its data. That increases code complexity slightly and is more difficult to read and understand afterwards. The core motivation for boost::variant was to maintain independence from Qt to allow for outsourcing the database code into a separate library (may be useful for other programs too).
Wrap the internal data representation (Element::PropertyVariant) into a separate class. Eventually, the type identification code too (Element::Property and Element::PropertyType).
Definition at line 89 of file element.h.
Member Typedef Documentation
typedef PropertyVariantVector::iterator Element::PropertyValueIterator
Definition at line 142 of file element.h.
typedef PropertyVariantVector::const_iterator Element::PropertyValueIteratorConst
Definition at line 141 of file element.h.
typedef boost::variant<int, std::string, double, complex> Element::PropertyVariant
Data type of a single property value.
Definition at line 136 of file element.h.
typedef std::vector<PropertyVariant> Element::PropertyVariantVector
Container for all defined property values, the data.
Definition at line 140 of file element.h.
typedef std::vector<Property> Element::PropertyVector
Container for all defined properties.
Definition at line 138 of file element.h.
typedef QPointer<Element> Element::Ptr
A guarded Pointer to such an Element.
Definition at line 93 of file element.h.
Member Enumeration Documentation
enum Element::Property
All properties of an Element in the database.
Enumerator:
SYMBOL_PROPERTY
Chemical symbol.
NAME_PROPERTY
Full name.
NUCLEONS_PROPERTY
Number of nucleons (aka atomic mass number A).
ELECTRONS_PROPERTY
Number of electrons (aka atomic number Z).
ATOMIC_MASS_PROPERTY
The atomic mass.
ABUNDANCE_PROPERTY
The natural abundance in the local environment of the Earth's crust and atmosphere.
NS_L_COHERENT_PROPERTY
Bound coherent neutron scattering length.
NS_L_INCOHERENT_PROPERTY
Bound incoherent neutron scattering length.
NS_CS_COHERENT_PROPERTY
Bound coherent neutron scattering cross section.
NS_CS_INCOHERENT_PROPERTY
Bound incoherent neutron scattering cross section.
NS_CS_TOTAL_PROPERTY
Total bound scattering cross section.
NS_CS_ABSORPTION_PROPERTY
Absorption cross section for 2200 m/s neutrons.
XRAY_ENERGY_PROPERTY
X-Ray Scattering factors as a function of energy.
Not used at the moment.
INVALID_PROPERTY
Invalid property.
Definition at line 96 of file element.h.
enum Element::PropertyType
The data type of a property to allow for convenient testing at runtime.
Enumerator:
INT_TYPE
Integer.
STRING_TYPE
Character string.
DOUBLE_TYPE
Floating point number.
COMPLEX_TYPE
Complex number with floating point.
INVALID_TYPE
Invalid.
Definition at line 128 of file element.h.
Constructor & Destructor Documentation
Element::Element ()
Initializes all properties of this Element.
Sets all properties to valid types and values accordingly. The values are valid regarding their Element::PropertyType but may not be valid from a physical point of view.
See also:
isValid()
Definition at line 47 of file element.cpp.
References COMPLEX_TYPE, defaultValue(), DOUBLE_TYPE, getProperty(), INT_TYPE, INVALID_PROPERTY_VALUE, mProperties, propertyCount(), and STRING_TYPE.
Element::~Element ()
Releases all memory.
Definition at line 69 of file element.cpp.
Member Function Documentation
void Element::addXrayCoefficient (double energy, double fp, double fpp)
Adds a new triple to the X-Ray scattering factors.
Overwrites existing triples with the same energy value.
Definition at line 158 of file element.cpp.
References mXrayCoefficients.
double Element::atomicMass () const
Provided for convenience.
See also:
ATOMIC_MASS_PROPERTY
Definition at line 193 of file element.cpp.
Element::PropertyValueIterator Element::begin () [private]
Returns a read/write iterator to the first of all property values.
Definition at line 241 of file element.cpp.
References mProperties.
Element::PropertyValueIteratorConst Element::beginConst () const
Returns a read-only iterator to the first of all property values.
Definition at line 175 of file element.cpp.
References mProperties.
Referenced by getProperty(), and operator<<().
int Element::defaultValue (int a, Element::Property p) [static, private]
Explicitly typified default value for property p.
Definition at line 283 of file element.cpp.
Referenced by Element(), and getValue().
double Element::defaultValue (double a, Element::Property p) [static, private]
Explicitly typified default value for property p.
Definition at line 286 of file element.cpp.
References ABUNDANCE_PROPERTY.
complex Element::defaultValue (complex a, Element::Property p) [static, private]
Explicitly typified default value for property p.
Definition at line 293 of file element.cpp.
std::string Element::defaultValue (std::string a, Element::Property p) [static, private]
Explicitly typified default value for property p.
Definition at line 299 of file element.cpp.
int Element::doNucleons () const [private, virtual]
Implementation of data access for cfp::ChemicalElementInterface.
Definition at line 271 of file element.cpp.
void Element::doSetNucleons (int n) [private, virtual]
Implementation of data access for cfp::ChemicalElementInterface.
Definition at line 277 of file element.cpp.
References NUCLEONS_PROPERTY, and setProperty().
void Element::doSetSymbol (const std::string & s) [private, virtual]
Implementation of data access for cfp::ChemicalElementInterface.
Definition at line 265 of file element.cpp.
References setProperty(), and SYMBOL_PROPERTY.
std::string Element::doSymbol () const [private, virtual]
Implementation of data access for cfp::ChemicalElementInterface.
Definition at line 259 of file element.cpp.
double Element::electrons () const
Provided for convenience.
See also:
ELECTRONS_PROPERTY
Definition at line 187 of file element.cpp.
Element::PropertyValueIterator Element::end () [private]
Returns a read/write iterator which points behind the last property value.
Definition at line 247 of file element.cpp.
References mProperties.
Element::PropertyValueIteratorConst Element::endConst () const
Returns a read-only iterator which points behind the last property value.
Definition at line 178 of file element.cpp.
References mProperties.
Referenced by operator<<().
Element::Property Element::getProperty (const PropertyValueIteratorConst & iter) const
Returns the Property of the specified property value iterator created with beginConst() or endConst();.
Definition at line 181 of file element.cpp.
References beginConst(), and getProperty().
Element::Property Element::getProperty (const PropertyValueIterator & iter) const [private]
Returns the Property of the specified property value iterator created with begin() or end();.
Definition at line 253 of file element.cpp.
References beginConst(), and getProperty().
Element::Property Element::getProperty (int index) [static]
Returns the Property with the specified index.
Definition at line 87 of file element.cpp.
References INVALID_PROPERTY.
Referenced by DataVisualizer::display(), DataVisualizer::draw(), Element(), getProperty(), DataVisualizer::retranslateUi(), and MainWindow::showElementData().
template<typename T > T Element::getValue (Property p) const [private]
Returns the value of given property p.
The chosen type must match that of the given property.
Definition at line 255 of file element.h.
References defaultValue(), propertyConst(), and propertyName().
bool Element::isValid () const
Tests this element for (physical) valid property values.
Definition at line 133 of file element.cpp.
References ABUNDANCE_PROPERTY, ATOMIC_MASS_PROPERTY, ELECTRONS_PROPERTY, NAME_PROPERTY, NUCLEONS_PROPERTY, propertyConst(), and SYMBOL_PROPERTY.
bool Element::isValidType (Property p, const PropertyVariant & var) [static]
Tests if the given property value matches the given property.
Definition at line 127 of file element.cpp.
References propertyType().
Referenced by setProperty().
bool Element::isValidVariant (const PropertyVariant & var) [static]
Tests a given property value for invalid type.
See also:
INVALID_TYPE, INVALID_PROPERTY_VALUE
Definition at line 95 of file element.cpp.
References INVALID_PROPERTY_VALUE.
Referenced by DataVisualizer::draw(), and MainWindow::toString().
complex Element::nslCoherent () const
Provided for convenience.
See also:
NS_L_COHERENT_PROPERTY
Definition at line 199 of file element.cpp.
Referenced by InputData::calcData().
complex Element::nslIncoherent () const
Provided for convenience.
See also:
NS_L_INCOHERENT_PROPERTY
Definition at line 205 of file element.cpp.
Referenced by InputData::calcData().
const Element::PropertyVariant & Element::propertyConst (Element::Property p) const
Returns the property value associated with the specified property.
Definition at line 302 of file element.cpp.
References mProperties.
Referenced by getValue(), and isValid().
int Element::propertyCount () [static]
Returns the overall number of available properties.
Definition at line 81 of file element.cpp.
Referenced by DataVisualizer::display(), Element(), DataVisualizer::retranslateUi(), and MainWindow::showElementData().
const char * Element::propertyName (Property p) [static]
Returns the name of a given property.
It is used to display a name in the GUI (after translation by Qt).
Definition at line 74 of file element.cpp.
References INVALID_PROPERTY, and mPropertyNames.
Referenced by getValue(), DataVisualizer::retranslateUi(), and MainWindow::showElementData().
Element::PropertyType Element::propertyType (Element::Property p) [static]
Returns the data type of a given property.
Definition at line 102 of file element.cpp.
References ABUNDANCE_PROPERTY, ATOMIC_MASS_PROPERTY, ELECTRONS_PROPERTY, NAME_PROPERTY, NS_CS_ABSORPTION_PROPERTY, NS_CS_COHERENT_PROPERTY, NS_CS_INCOHERENT_PROPERTY, NS_CS_TOTAL_PROPERTY, NS_L_COHERENT_PROPERTY, NS_L_INCOHERENT_PROPERTY, NUCLEONS_PROPERTY, and SYMBOL_PROPERTY.
Referenced by DataVisualizer::display(), DataVisualizer::draw(), and isValidType().
template<typename T > bool Element::setProperty (Property p, const T & value)
Sets the specified property to the provided value.
Definition at line 267 of file element.h.
References ABUNDANCE_PROPERTY, ATOMIC_MASS_PROPERTY, ELECTRONS_PROPERTY, INVALID_PROPERTY, isValidType(), and mProperties.
Referenced by doSetNucleons(), and doSetSymbol().
const MapTriple & Element::xrayCoefficients () const
Provides read-only access to the X-Ray scattering factors.
See the description above.
Definition at line 152 of file element.cpp.
References mXrayCoefficients.
Referenced by operator<<().
Field Documentation
const int Element::INVALID_PROPERTY_VALUE = -2 [static]
Default value for properties with invalid type.
See also:
PropertyType
Definition at line 145 of file element.h.
Referenced by Element(), and isValidVariant().
PropertyVariantVector Element::mProperties [private]
Container for all property values.
Definition at line 247 of file element.h.
Referenced by begin(), beginConst(), Element(), end(), endConst(), propertyConst(), and setProperty().
const char * Element::mPropertyNames [static, private]
Initial value:
 {
        "symbol",
        "name",
        "nucleons",
        "electrons",
        "atomic mass",
        "abundance",
        "coherent length",
        "incoherent length",
        "coherent cross section",
        "incoherent cross section",
        "total cross section",
        "absorption cross section",
        "xray energies"
}
Points to the names of all properties.
Definition at line 249 of file element.h.
Referenced by propertyName().
MapTriple Element::mXrayCoefficients [private]
Container for X-Ray scattering factors.
Definition at line 251 of file element.h.
Referenced by addXrayCoefficient(), and xrayCoefficients().
The documentation for this class was generated from the following files:
element.h
element.cpp