qSLDcalc: DataVisualizer Class Reference
DataVisualizer Class Reference
Displays all known chemical elements in a two-dimensional viewport organized by one of their property, selected by the user.
#include <datavisualizer.h>
Public Slots
void show ()
Shows this data visualization window to the user and selects the first property to display initially.
Signals
void elementLinkActivated (const QString &link)
Emits a link text of the element whose detailed information should be shown in the main window and which was previously clicked at by the user.
Public Member Functions
DataVisualizer (MainWindow *parent, ElementDatabase &db)
Constructor.
void retranslateUi ()
Retranslates this subwindow at runtime.
Static Public Member Functions
static QString getLinkText (const cfp::ChemicalElementInterface &e)
Generate a link text for the specified element to display detailed element data in the mainwindow.
Private Types
typedef QPointer< QGraphicsScene > SceneType
Shortcut.
typedef QPointer< QGraphicsView > ViewType
Shortcut.
Private Slots
void display (int index)
Displays and draws all chemical elements sorted by their property specified by index.
void emitElementLinkActivated (const QString &link)
Signal forwarder to display element details in the mainwindow.
Private Member Functions
void draw (SceneType scene, qreal &lastXPos, Element::Ptr e, int propertyIndex)
Draws the selected property of an element to the scene in a way that it doesn't overlap with other items.
void setItemPos (QGraphicsItem *item, QPointF pos)
Sets the position of an item in a graphics scene in a way it doesn't collide or overlap with other items.
void selectIndex (int index)
Selects another Element characteristic and rebuilds the graphics scene.
void adjustSize (void)
Adjusts the height of the data visualization window to show as much data elements as possible.
Private Attributes
ElementDatabase::Ptr mDB
A link to the data base with all known chemical elements.
MainWindow * mMainWindow
The parent window.
Static Private Attributes
static const qreal itemMargin = 5.0
Margin around items to not contact each other or the graphics view boundary.
static const int initialSelection = 0
Initially selected element characteristic to show.
Detailed Description
Displays all known chemical elements in a two-dimensional viewport organized by one of their property, selected by the user.
Definition at line 42 of file datavisualizer.h.
Member Typedef Documentation
typedef QPointer<QGraphicsScene> DataVisualizer::SceneType [private]
Shortcut.
Definition at line 46 of file datavisualizer.h.
typedef QPointer<QGraphicsView> DataVisualizer::ViewType [private]
Shortcut.
Definition at line 47 of file datavisualizer.h.
Constructor & Destructor Documentation
DataVisualizer::DataVisualizer (MainWindow * parent, ElementDatabase & db)
Constructor.
Parameters:
[in,out] parent Parent window (main window).
[in,out] db Database of all known chemical elements. Uses read access only. Because of QPointer it's read/write formally.
Definition at line 31 of file datavisualizer.cpp.
References display(), and initialSelection.
Member Function Documentation
void DataVisualizer::adjustSize (void) [private]
Adjusts the height of the data visualization window to show as much data elements as possible.
Definition at line 201 of file datavisualizer.cpp.
Referenced by display().
void DataVisualizer::display (int index) [private, slot]
Displays and draws all chemical elements sorted by their property specified by index.
Parameters:
[in] index Property to sort all chemical elements by.
See also:
Element::getProperty(int index)
Definition at line 69 of file datavisualizer.cpp.
References adjustSize(), Element::COMPLEX_TYPE, draw(), Element::getProperty(), itemMargin, mDB, Element::propertyCount(), Element::propertyType(), and Element::STRING_TYPE.
Referenced by DataVisualizer(), and selectIndex().
void DataVisualizer::draw (SceneType scene, qreal & lastXPos, Element::Ptr e, int propertyIndex) [private]
Draws the selected property of an element to the scene in a way that it doesn't overlap with other items.
Parameters:
[in,out] scene The QGraphicsScene to draw to.
[in,out] lastXPos Position in x direction of the last element drawed. Assumes, the items are sorted by the selected property in ascending order.
[in] e The Element whose property should be drawn.
[in] propertyIndex The index of the element property to draw.
See also:
Element::getProperty(int index)
Definition at line 152 of file datavisualizer.cpp.
References Element::COMPLEX_TYPE, emitElementLinkActivated(), getLinkText(), Element::getProperty(), Element::isValidVariant(), itemMargin, mMainWindow, Element::NUCLEONS_PROPERTY, Element::propertyType(), setItemPos(), Element::STRING_TYPE, and MainWindow::toString().
Referenced by display().
void DataVisualizer::elementLinkActivated (const QString & link) [signal]
Emits a link text of the element whose detailed information should be shown in the main window and which was previously clicked at by the user.
Referenced by emitElementLinkActivated().
void DataVisualizer::emitElementLinkActivated (const QString & link) [private, slot]
Signal forwarder to display element details in the mainwindow.
Is called by every single item drawn in the graphics scene.
Parameters:
[in] link The link text.
See also:
getLinkText()
Definition at line 264 of file datavisualizer.cpp.
References elementLinkActivated().
Referenced by draw().
QString DataVisualizer::getLinkText (const cfp::ChemicalElementInterface & e) [static]
Generate a link text for the specified element to display detailed element data in the mainwindow.
Example for H4:
 <style>a{text-decoration:none;}</style><a href="H">H<sub>4</sub></a>
Example for O:
 <style>a{text-decoration:none;}</style><a href="O">O</a>
Parameters:
[in] e The chemical element to generate a link for.
Returns:
The link text.
See also:
MainWindow::showElementData(const QString& key)
Definition at line 270 of file datavisualizer.cpp.
References ElementDatabase::makeKey().
Referenced by draw(), and MainWindow::setFormattedFormula().
void DataVisualizer::retranslateUi ()
Retranslates this subwindow at runtime.
Definition at line 282 of file datavisualizer.cpp.
References Element::getProperty(), Element::propertyCount(), Element::propertyName(), and selectIndex().
Referenced by MainWindow::retranslateUi().
void DataVisualizer::selectIndex (int index) [private]
Selects another Element characteristic and rebuilds the graphics scene.
Parameters:
[in] index The index of the element property to draw.
See also:
Element::getProperty(int index)
Definition at line 257 of file datavisualizer.cpp.
References display().
Referenced by retranslateUi(), and show().
void DataVisualizer::setItemPos (QGraphicsItem * item, QPointF pos) [private]
Sets the position of an item in a graphics scene in a way it doesn't collide or overlap with other items.
Parameters:
[in,out] item The item to position in the scene.
[in] pos The desired position of the item. To avoid overlapping, it is changed in vertical direction (y) only.
Definition at line 221 of file datavisualizer.cpp.
References itemMargin.
Referenced by draw().
void DataVisualizer::show () [slot]
Shows this data visualization window to the user and selects the first property to display initially.
Definition at line 250 of file datavisualizer.cpp.
References initialSelection, and selectIndex().
Field Documentation
const int DataVisualizer::initialSelection = 0 [static, private]
Initially selected element characteristic to show.
Definition at line 132 of file datavisualizer.h.
Referenced by DataVisualizer(), and show().
const qreal DataVisualizer::itemMargin = 5.0 [static, private]
Margin around items to not contact each other or the graphics view boundary.
Definition at line 130 of file datavisualizer.h.
Referenced by display(), draw(), and setItemPos().
ElementDatabase::Ptr DataVisualizer::mDB [private]
A link to the data base with all known chemical elements.
Definition at line 127 of file datavisualizer.h.
Referenced by display().
MainWindow* DataVisualizer::mMainWindow [private]
The parent window.
Definition at line 134 of file datavisualizer.h.
Referenced by draw().
The documentation for this class was generated from the following files:
datavisualizer.h
datavisualizer.cpp