qSLDcalc: InputData Class Reference
InputData Class Reference
Stores GUI input data and performs compound calculations.
#include <inputdata.h>
Public Member Functions
InputData (ElementDatabase &db)
Constructor.
void set (const QString &key, const QVariant &var)
Adds data.
void setInit (const QString &key, const QVariant &var)
Adds data to the initial set which is queried at GUI reset.
QVariant get (const QString &key) const
Returns data with the specified key.
QVariant getInit (const QString &key) const
Returns data with the specified key from the initial set which is queried at GUI reset.
void interpretFormula (const QString &formulaKey)
Parses the given formula character string.
const cfp::Compound & empiricalFormula () const
Returns the compound from recent formula parsing.
void addAlias (const QString &name)
Adds a new alias to the element database of type ElementDatabase.
Private Types
typedef QHash< QString, QVariant > QHashType
Hash table type for internal data organization.
typedef QPair
< cfp::CompoundElement,
Element::Ptr > ElemPair
Combined type for the chemical element signature from a formula and the element dataset from the database.
typedef QList< ElemPair > CompleteList
A List of combined element types.
Private Member Functions
void set (QHashType &h, const QString &key, const QVariant &var)
Adds data.
QVariant get (const QHashType &h, const QString &key) const
Returns data with the specified key.
void buildCompleteList (CompleteList &list, const cfp::Compound &comp)
Adds references to database elements to a given compound (from parsing).
void calcData (const CompleteList &cl)
Calculates all information which shall be displayed in the main window for a given formula.
double calcElectrons (const CompleteList &cl, QVariantMap &partialElectrons)
Calculates total and partial number of electrons.
void calcMassAndVolume (const CompleteList &cl, QVariantMap &partialVolume, double &totalMass, double &totalVolume)
Calculates total and partial mass and volume.
void calcNSL (const CompleteList &cl, double totalVolume, QVariantMap &neutron, complex(Element::*func)(void) const, const char *slText, const char *sldText)
Calculates total and partial neutron scattering lengths and densities.
void calcXrayEnergies (const CompleteList &cl, const QVariantMap &partialVolumes, const QVariantMap &partialElectrons)
Calculates total and partial X-Ray scattering coefficients as well as total and partial X-Ray scattering length densities.
bool calcXrayCoefficients (double &fp, double &fpp, Element::Ptr ep, double coeff, double energy)
Helper of calcXrayEnergies().
Private Attributes
ElementDatabase::Ptr mDB
A reference to the element database.
QHashType mInitData
Initial input data (used for reset).
QHashType mData
Input data and intermediate calculation results (buffer).
cfp::Parser mFormulaParser
Chemical formula parser.
Friends
std::ostream & std::operator<< (std::ostream &o, const InputData &ind)
Detailed Description
Stores GUI input data and performs compound calculations.
User input from the GUI is stored in hash tables with QVariant data type. It is parsed on request by interpretFormula() which gets detailed chemical element characteristics from the associated ElementDatabase, calculates all total and partial compound characteristics and stores the results in the hash table where it can be retrieved on request by get().
Currently, the results are stored with the following keys in a hierarchical structure by use of QVariantMap as a container for further QVariant types:
 - "number of electrons"                     QVariantMap
     - "value"                               total number: QVariant(double)
     <one entry per element>                 [chem. symbol, QVariant(double)]
 - "molecular mass g/mol"                    QVariantMap
     - "value"                               total mass: QVariant(double)
     - "partial masses g/mol"                QVariantMap
         <one entry per element>             [chem. symbol, QVariant(double)]
     - "mass ratios %"                       QVariantMap
         <one entry per element>             [chem. symbol, QVariant(double)]
 - "molecular volume nm^3"                   QVariantMap
     - "value"                               total volume: QVariant(double)
     <one entry per element>                 [chem. symbol, QVariant(double)]
 - "xray scattering"                         QVariantMap
     - "f'"                                  QVariantMap
       - "value"                             total 1.deriv scattering coeff.: QVariant(double)
       <one entry per element>               [chem. symbol, QVariant(double)]
     - "f''"                                 QVariantMap
       - "value"                             total 2.deriv scattering coeff.: QVariant(double)
       <one entry per element>               [chem. symbol, QVariant(double)]
     - "SLD cm^-2"                           QVariantMap
       - "value"                             total complex X-Ray SLD: QVariant(complex)
       <one entry per element>               [chem. symbol, QVariant(complex)]
 - "neutron scattering"                      QVariantMap
     - "coherent scattering length 1e-15m"   total complex value: QVariant(complex)
     - "SLD coherent 1/cm^2"                 QVariantMap
         - "value"                           total complex value: QVariant(complex)
         <one entry per element>             [chem. symbol, QVariant(complex)]
     - "incoherent scattering length 1e-15m" total complex value: QVariant(complex)
     - "SLD incoherent 1/cm^2"               QVariantMap
         - "value"                           total complex value: QVariant(complex)
         <one entry per element>             [chem. symbol, QVariant(complex)]
 QVariant(complex) ==> QVariant( QVariantList( QVariant(double), QVariant(double) ))
Definition at line 96 of file inputdata.h.
Member Typedef Documentation
typedef QList<ElemPair> InputData::CompleteList [private]
A List of combined element types.
Can be interpreted as a compound (from formula parsing) extended by pointers to the according database elements.
Definition at line 108 of file inputdata.h.
typedef QPair<cfp::CompoundElement, Element::Ptr> InputData::ElemPair [private]
Combined type for the chemical element signature from a formula and the element dataset from the database.
Definition at line 103 of file inputdata.h.
typedef QHash<QString, QVariant> InputData::QHashType [private]
Hash table type for internal data organization.
Definition at line 99 of file inputdata.h.
Constructor & Destructor Documentation
InputData::InputData (ElementDatabase & db)
Constructor.
Definition at line 32 of file inputdata.cpp.
Member Function Documentation
void InputData::addAlias (const QString & name)
Adds a new alias to the element database of type ElementDatabase.
Parameters:
[in] name Alias name.
Definition at line 62 of file inputdata.cpp.
References empiricalFormula(), and mDB.
Referenced by MainWindow::addAlias().
void InputData::buildCompleteList (CompleteList & list, const cfp::Compound & comp) [private]
Adds references to database elements to a given compound (from parsing).
For every element in the compound comp it queries the element database and adds a reference to it in list. If not found, throws ErrorUnknownElement.
Parameters:
[out] list List of chemical element signatures combined with element database references.
[in] comp A list of chemical element signatures from parsing a formula.
Definition at line 92 of file inputdata.cpp.
References calcData(), and mDB.
Referenced by interpretFormula().
void InputData::calcData (const CompleteList & cl) [private]
Calculates all information which shall be displayed in the main window for a given formula.
Parameters:
[in] cl The completely defined formula.
Definition at line 354 of file inputdata.cpp.
References calcElectrons(), calcMassAndVolume(), calcNSL(), calcXrayEnergies(), Element::nslCoherent(), and Element::nslIncoherent().
Referenced by buildCompleteList().
double InputData::calcElectrons (const CompleteList & cl, QVariantMap & partialElectrons) [private]
Calculates total and partial number of electrons.
Parameters:
[in] cl Complete formula.
[out] partialElectrons Map with the number of electrons for each chemical element (its symbol) in the formula.
Definition at line 121 of file inputdata.cpp.
Referenced by calcData().
void InputData::calcMassAndVolume (const CompleteList & cl, QVariantMap & partialVolume, double & totalMass, double & totalVolume) [private]
Calculates total and partial mass and volume.
Parameters:
[in] cl Complete formula.
[out] partialVolume Map with the volume fraction for each chemical element (its symbol) in the formula.
[out] totalMass Total mass of the compound.
[out] totalVolume Total Volume of the compound.
Definition at line 139 of file inputdata.cpp.
References avogadro().
Referenced by calcData().
void InputData::calcNSL (const CompleteList & cl, double totalVolume, QVariantMap & neutron, complex(Element::*)(void) const func, const char * slText, const char * sldText) [private]
Calculates total and partial neutron scattering lengths and densities.
Parameters:
[in] cl Complete formula.
[in] totalVolume The total volume of the compound.
[in,out] neutron A Map which contains all neutron scattering related data finally.
[in] func Member function of Element to retrieve the neutron scattering length (coherent or incoherent).
[in] slText Key for storing the total neutron scattering length.
[in] sldText Key for storing the partial neutron scattering densities.
Definition at line 186 of file inputdata.cpp.
References addComplex2Map().
Referenced by calcData().
bool InputData::calcXrayCoefficients (double & fp, double & fpp, Element::Ptr ep, double coeff, double energy) [private]
Helper of calcXrayEnergies().
Parameters:
[out] fp Xray scattering coefficient (first derivation)
[out] fpp Xray scattering coefficient (second derivation)
[in] elemIt Iterator to an element in a CompleteList (to calculate the coefficients for).
[in] energy User specified Xray energy.
Returns:
True, on success. False, if the given energy value is out of range.
Definition at line 227 of file inputdata.cpp.
References interpolate().
Referenced by calcXrayEnergies().
void InputData::calcXrayEnergies (const CompleteList & cl, const QVariantMap & partialVolumes, const QVariantMap & partialElectrons) [private]
Calculates total and partial X-Ray scattering coefficients as well as total and partial X-Ray scattering length densities.
Parameters:
[in] cl Complete formula.
[in] partialVolumes Partial volume fractions of the compound.
[in] partialElectrons Partial number of electrons of the compound.
Definition at line 270 of file inputdata.cpp.
References addComplex2Map(), calcXrayCoefficients(), mDB, and sldXray().
Referenced by calcData().
const cfp::Compound & InputData::empiricalFormula () const
Returns the compound from recent formula parsing.
Definition at line 56 of file inputdata.cpp.
References mFormulaParser.
Referenced by addAlias(), and MainWindow::setFormattedFormula().
QVariant InputData::get (const QHashType & h, const QString & key) const [private]
Returns data with the specified key.
Parameters:
[in] h A hash table to use for storing data.
[in] key Name of the entry.
Returns:
Data associated to the specified key.
Definition at line 41 of file inputdata.cpp.
QVariant InputData::get (const QString & key) const
Returns data with the specified key.
Parameters:
[in] key Name of the entry.
Returns:
Data associated to the specified key.
Definition at line 50 of file inputdata.cpp.
References mData.
Referenced by MainWindow::resultAddData(), and MainWindow::resultAddInput().
QVariant InputData::getInit (const QString & key) const
Returns data with the specified key from the initial set which is queried at GUI reset.
Parameters:
[in] key Name of the entry.
Returns:
Data associated to the specified key.
Definition at line 53 of file inputdata.cpp.
References mInitData.
Referenced by MainWindow::resetInput().
void InputData::interpretFormula (const QString & formulaKey)
Parses the given formula character string.
Stores the resulting compound in the database with the supplied formula as key.
Parameters:
[in] formulaKey The formula to interpret.
Definition at line 71 of file inputdata.cpp.
References buildCompleteList(), mData, and mFormulaParser.
Referenced by MainWindow::doCalc().
void InputData::set (const QString & key, const QVariant & var)
Adds data.
Parameters:
[in] key Name of the entry.
[in] var Data to add.
Definition at line 44 of file inputdata.cpp.
References mData.
Referenced by MainWindow::saveInput().
void InputData::set (QHashType & h, const QString & key, const QVariant & var) [private]
Adds data.
Parameters:
[in,out] h A hash table to use for storing data.
[in] key Name of the entry.
[in] var Data to add.
Definition at line 38 of file inputdata.cpp.
void InputData::setInit (const QString & key, const QVariant & var)
Adds data to the initial set which is queried at GUI reset.
Parameters:
[in] key Name of the entry.
[in] var Data to add.
Definition at line 47 of file inputdata.cpp.
References mInitData.
Referenced by MainWindow::saveInitialInput().
Friends And Related Function Documentation
std::ostream& std::operator<< (std::ostream & o, const InputData & ind) [friend]
Field Documentation
QHashType InputData::mData [private]
Input data and intermediate calculation results (buffer).
Definition at line 240 of file inputdata.h.
Referenced by get(), interpretFormula(), std::operator<<(), and set().
ElementDatabase::Ptr InputData::mDB [private]
A reference to the element database.
Definition at line 236 of file inputdata.h.
Referenced by addAlias(), buildCompleteList(), and calcXrayEnergies().
cfp::Parser InputData::mFormulaParser [private]
Chemical formula parser.
Definition at line 242 of file inputdata.h.
Referenced by empiricalFormula(), and interpretFormula().
QHashType InputData::mInitData [private]
Initial input data (used for reset).
Definition at line 238 of file inputdata.h.
Referenced by getInit(), and setInit().
The documentation for this class was generated from the following files:
inputdata.h
inputdata.cpp