qSLDcalc: MainWindow Class Reference
MainWindow Class Reference
Main window GUI configuration and management.
#include <mainwindow.h>
Data Structures
struct FormEntry
Required information of an user input field for dynamical processing at runtime.
class QStringFromBoostVariant
Converts a boost variant into a QString.
Public Member Functions
MainWindow (QApplication &app, ElementDatabase &db)
Creates the main window.
QString toString (const Element::PropertyVariant &var) const
Converts any property of a chemical element to a localization aware character string.
Private Slots
void about ()
Raises a message box with general information about the program.
void loadLanguage (const QString &filename)
Loads another language file and triggers a retranslate of the GUI.
void selectDefaultLang ()
Tries to determine the desired language from the system locale settings.
void resetInput ()
Resets the GUI input fields to initial values.
void doCalc ()
Calculates compound characteristics from current GUI input data.
void addAlias ()
Adds an alias for the current compound, i.e.
void copyResultTableSelection ()
Copies the current selection of the result to the clipboard.
void rebuildResultTable ()
Fills the tabular widget with the results of the last calculation, i.e.
void useSystemLocaleTriggered ()
void showElementData (const QString &key)
Displays detailed information of a chemical element in the tabular result widget.
void expandItem (const QModelIndex &index=QModelIndex())
Expands an item in the tabular result widget.
void expandAll ()
Expands all items in the tabular result widget.
void collapseAll ()
Collapses all items in the tabular result widget.
Private Member Functions
void addActions ()
Sets up entries, i.e.
void retranslateUi ()
Retranslates the entire application at runtime.
void updateLangActions (QMenu *menuLang)
Updates the menu of available languages.
void saveInitialInput ()
Stores user-defined input data as initial settings (for reset later).
void saveInput ()
Stores user-defined input data for further processing.
void fillResultTable ()
Populates the tabular result widget with recent calculation results from InputData.
void clearResultTable ()
Removes all entries from the tabular result widget.
void resultAddData (const char *key, bool expand)
Inserts a new item to the tabular result widget.
void appendVariant (QStandardItem *parent, const QString &name, const QVariant &var)
Appends a QVariant to the tabular result widget.
void appendVariantMap (QStandardItem *parent, const QString &name, const QVariantMap &map)
Appends a QVariantMap to the tabular result widget.
void resultAddInput ()
Adds the user input to the result output.
QString qstringFromVariant (const QVariant &var) const
Converts a QVariant to a character string.
QString qstringFromDouble (double d) const
Converts a double to a character string.
QString qstringFromComplex (complex c) const
Converts a complex number to a character string.
void setFormattedFormula ()
Displays the HTML formatted formula with links for detailed information of every chemical element.
bool formulaIsEmpty () const
Tests if there is a formula in the input field currently.
Private Attributes
QMenu * menuFile
Menubar entry file.
QMenu * menuTools
Menubar entry tools.
QMenu * menuLang
Menubar entry language.
QMenu * menuHelp
Menubar entry help.
QApplication * mApp
Reference to the parent application.
FormulaCompleter * mCompleter
Formula piecewise completion feature.
QTranslator mTranslator
Translates all GUI texts.
QPalette mFormulaDefaultPalette
To restore the original color of the input formula text.
LangActionList mLangActionList
Actions for switching to a certain available language.
QDir mLangPath
Directory path to search for translations.
QString mLangFile
QLocale mLocale
Currently loaded language file.
QString mAboutTitle
Current locale for double -> string.
QString mAboutText
InputData mInputData
Stores input data and calculates compound characteristics.
ElementDatabase::Ptr mDB
Database of all known chemical elements.
DataVisualizer mDataVisualizer
Visualizes selected characteristics of all known chemical elements.
QStandardItemModel mModel
Backend model for the tabular result widget.
QList< FormEntry > mFormEntries
List of all user input fields to process.
Detailed Description
Main window GUI configuration and management.
Handling of GUI input fields: The constructor adds each user input field to the list MainWindow::mFormEntries. When the calculate button is pressed, all fields are read dynamically (based on the property system provided by QObject) and their data is stored in the InputData object with their object name as key. For example, the value of the input field for density is stored in InputData with the key "ntrDensity", as it's the object name (and variable name) of the density spinbox.
See also:
saveInitialInput(), saveInput(), resetInput()
Localization issues: The results can be exported in ASCII semicolon separated format. To simplify further work with this data, the user can disable the use of system settings for the decimal operator (language menu -> checkbox). This makes it possible to have all text translated but keeping the dot as decimal operator. In consequence, all floating-point to character string conversion have to be handled by the respective member functions:
See also:
qstringFromVariant(), qstringFromComplex(), qstringFromDouble()
Todo:
Eventually, rewrite the GUI with python to avoid the hassle with memory management. Keep the backend in C++ (InputData, ElementDatabase).
Definition at line 137 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QApplication & app, ElementDatabase & db)
Creates the main window.
Parameters:
[in,out] app QApplication object we are associated with
[in,out] db Entirely populated chemical element database.
Definition at line 37 of file mainwindow.cpp.
References about(), addActions(), addAlias(), collapseAll(), copyResultTableSelection(), doCalc(), expandAll(), expandItem(), mApp, mCompleter, mDataVisualizer, menuFile, menuHelp, menuLang, menuTools, mFormEntries, mFormulaDefaultPalette, mLangPath, mModel, mTranslator, resetInput(), saveInitialInput(), selectDefaultLang(), showElementData(), and useSystemLocaleTriggered().
Member Function Documentation
void MainWindow::about () [private, slot]
Raises a message box with general information about the program.
Definition at line 203 of file mainwindow.cpp.
References mAboutText, and mAboutTitle.
Referenced by MainWindow().
void MainWindow::addActions () [private]
Sets up entries, i.e.
available actions, in the menubar and the tabular result widget.
Definition at line 244 of file mainwindow.cpp.
References menuFile, menuHelp, menuLang, and menuTools.
Referenced by MainWindow().
void MainWindow::addAlias () [private, slot]
Adds an alias for the current compound, i.e.
formula.
Todo:
Remember expand/collapse the state of all cells when raising the add-alias dialog, i.e. calculating the formula (doCalc()).
Definition at line 321 of file mainwindow.cpp.
References InputData::addAlias(), doCalc(), formulaIsEmpty(), mInputData, and AliasNameDialog::name().
Referenced by MainWindow().
void MainWindow::appendVariant (QStandardItem * parent, const QString & name, const QVariant & var) [private]
Appends a QVariant to the tabular result widget.
This is the most generic case. Helper for fillResultTable()
Parameters:
[in,out] parent Item to add this QVariant to. Root item of the tabular widget for top-level position.
[in] name Display name of the new item.
[in] var QVariant to add.
Definition at line 453 of file mainwindow.cpp.
References appendVariantMap(), and qstringFromVariant().
Referenced by appendVariantMap(), and resultAddData().
void MainWindow::appendVariantMap (QStandardItem * parent, const QString & name, const QVariantMap & map) [private]
Appends a QVariantMap to the tabular result widget.
Specialized for a map of variants. Helper for fillResultTable()
Parameters:
[in,out] parent Item to add this QVariantMap to. Root item of the tabular widget for top-level position.
[in] name Display name of the new item.
[in] map QVariantMap to add.
Definition at line 419 of file mainwindow.cpp.
References appendVariant(), and qstringFromVariant().
Referenced by appendVariant().
void MainWindow::clearResultTable () [private]
Removes all entries from the tabular result widget.
Definition at line 408 of file mainwindow.cpp.
References mModel.
Referenced by rebuildResultTable(), resetInput(), and showElementData().
void MainWindow::collapseAll () [private, slot]
Collapses all items in the tabular result widget.
Definition at line 689 of file mainwindow.cpp.
References expandItem().
Referenced by MainWindow().
void MainWindow::copyResultTableSelection () [private, slot]
Copies the current selection of the result to the clipboard.
Exports the selected rows and columns of the tabular widget as semicolon separated dataset. The content of unselected cells is not copied but the structure is preserved (empty cells).
Definition at line 562 of file mainwindow.cpp.
References appendSubItems(), mApp, and mModel.
Referenced by MainWindow().
void MainWindow::doCalc () [private, slot]
Calculates compound characteristics from current GUI input data.
Definition at line 296 of file mainwindow.cpp.
References InputData::interpretFormula(), mFormulaDefaultPalette, mInputData, rebuildResultTable(), and saveInput().
Referenced by addAlias(), MainWindow(), and showElementData().
void MainWindow::expandAll () [private, slot]
Expands all items in the tabular result widget.
Definition at line 683 of file mainwindow.cpp.
References expandItem().
Referenced by MainWindow().
void MainWindow::expandItem (const QModelIndex & index = QModelIndex()) [private, slot]
Expands an item in the tabular result widget.
Parameters:
[in] index Index of the item to expand.
Definition at line 695 of file mainwindow.cpp.
Referenced by collapseAll(), expandAll(), and MainWindow().
void MainWindow::fillResultTable () [private]
Populates the tabular result widget with recent calculation results from InputData.
Definition at line 346 of file mainwindow.cpp.
References mModel, resultAddData(), resultAddInput(), and setFormattedFormula().
Referenced by rebuildResultTable().
bool MainWindow::formulaIsEmpty () const [private]
Tests if there is a formula in the input field currently.
Definition at line 717 of file mainwindow.cpp.
Referenced by addAlias(), rebuildResultTable(), and setFormattedFormula().
void MainWindow::loadLanguage (const QString & filename) [private, slot]
Loads another language file and triggers a retranslate of the GUI.
Parameters:
[in] filename Absolute file name to load.
Definition at line 126 of file mainwindow.cpp.
References mLangFile, mLangPath, mTranslator, and retranslateUi().
Referenced by selectDefaultLang(), updateLangActions(), and useSystemLocaleTriggered().
QString MainWindow::qstringFromComplex (complex c) const [private]
Converts a complex number to a character string.
Accounts for the locale settings of the MainWindow.
Definition at line 368 of file mainwindow.cpp.
References qstringFromDouble().
Referenced by MainWindow::QStringFromBoostVariant::operator()(), and qstringFromVariant().
QString MainWindow::qstringFromDouble (double d) const [private]
Converts a double to a character string.
Accounts for the locale settings of the MainWindow.
Definition at line 363 of file mainwindow.cpp.
References mLocale.
Referenced by MainWindow::QStringFromBoostVariant::operator()(), qstringFromComplex(), qstringFromVariant(), and showElementData().
QString MainWindow::qstringFromVariant (const QVariant & var) const [private]
Converts a QVariant to a character string.
Special handling of floating point numbers.
See also:
qstringFromDouble(), qstringFromComplex()
Definition at line 382 of file mainwindow.cpp.
References qstringFromComplex(), and qstringFromDouble().
Referenced by appendVariant(), appendVariantMap(), and resultAddInput().
void MainWindow::rebuildResultTable () [private, slot]
Fills the tabular widget with the results of the last calculation, i.e.
formula parsing.
Definition at line 413 of file mainwindow.cpp.
References clearResultTable(), fillResultTable(), and formulaIsEmpty().
Referenced by doCalc(), and retranslateUi().
void MainWindow::resetInput () [private, slot]
Resets the GUI input fields to initial values.
Definition at line 285 of file mainwindow.cpp.
References clearResultTable(), InputData::getInit(), mFormEntries, mInputData, MainWindow::FormEntry::propertyName, setFormattedFormula(), and MainWindow::FormEntry::widget.
Referenced by MainWindow().
void MainWindow::resultAddData (const char * key, bool expand) [private]
Inserts a new item to the tabular result widget.
Helper for fillResultTable()
Parameters:
[in] key Key of the dataset within InputData.
[in] expand If true, this entry will be expanded in the underlying QTreeView.
Definition at line 469 of file mainwindow.cpp.
References appendVariant(), InputData::get(), mInputData, and mModel.
Referenced by fillResultTable().
void MainWindow::resultAddInput () [private]
Adds the user input to the result output.
Enables the user to export this data together with the results for improved consistency. Helper for fillResultTable()
Definition at line 488 of file mainwindow.cpp.
References InputData::get(), MainWindow::FormEntry::label, mFormEntries, mInputData, mModel, qstringFromVariant(), and MainWindow::FormEntry::widget.
Referenced by fillResultTable().
void MainWindow::retranslateUi () [private]
Retranslates the entire application at runtime.
Definition at line 141 of file mainwindow.cpp.
References mAboutText, mAboutTitle, mDataVisualizer, menuFile, menuHelp, menuLang, menuTools, rebuildResultTable(), DataVisualizer::retranslateUi(), and updateLangActions().
Referenced by loadLanguage().
void MainWindow::saveInitialInput () [private]
Stores user-defined input data as initial settings (for reset later).
Definition at line 266 of file mainwindow.cpp.
References mFormEntries, mInputData, MainWindow::FormEntry::propertyName, InputData::setInit(), and MainWindow::FormEntry::widget.
Referenced by MainWindow().
void MainWindow::saveInput () [private]
Stores user-defined input data for further processing.
Definition at line 275 of file mainwindow.cpp.
References mFormEntries, mInputData, MainWindow::FormEntry::propertyName, InputData::set(), and MainWindow::FormEntry::widget.
Referenced by doCalc().
void MainWindow::selectDefaultLang () [private, slot]
Tries to determine the desired language from the system locale settings.
On failure, selects the english translation. Called on startup.
Definition at line 109 of file mainwindow.cpp.
References loadLanguage(), and mLangPath.
Referenced by MainWindow(), and updateLangActions().
void MainWindow::setFormattedFormula () [private]
Displays the HTML formatted formula with links for detailed information of every chemical element.
Definition at line 332 of file mainwindow.cpp.
References InputData::empiricalFormula(), formulaIsEmpty(), DataVisualizer::getLinkText(), and mInputData.
Referenced by fillResultTable(), and resetInput().
void MainWindow::showElementData (const QString & key) [private, slot]
Displays detailed information of a chemical element in the tabular result widget.
Is connected to MainWindow::lblFormattedFormula.linkActivated() and DataVisualizer::elementLinkActivated().
Todo:
Translate chemical element names when displayed. They appear as regular data entries in the database and are not processed further, atm.
Parameters:
[in] key Database key for the chemical element to query. See ElementDatabase::KeyType for details.
Definition at line 602 of file mainwindow.cpp.
References addModelEntry(), clearResultTable(), doCalc(), Element::getProperty(), mDB, mModel, Element::NS_L_COHERENT_PROPERTY, Element::NUCLEONS_PROPERTY, Element::propertyCount(), Element::propertyName(), qstringFromDouble(), and toString().
Referenced by MainWindow().
QString MainWindow::toString (const Element::PropertyVariant & var) const
Converts any property of a chemical element to a localization aware character string.
See also:
QStringFromBoostVariant
Parameters:
[in] var Property of an database element to convert.
Returns:
The generated character string.
Definition at line 593 of file mainwindow.cpp.
References Element::isValidVariant().
Referenced by DataVisualizer::draw(), and showElementData().
void MainWindow::updateLangActions (QMenu * menuLang) [private]
Updates the menu of available languages.
Searches the language directory for language files and creates a menu entry for each such file.
Parameters:
[in,out] menuLang Language switching menu.
Definition at line 209 of file mainwindow.cpp.
References loadLanguage(), mLangActionList, mLangPath, and selectDefaultLang().
Referenced by retranslateUi().
void MainWindow::useSystemLocaleTriggered () [private, slot]
Definition at line 183 of file mainwindow.cpp.
References loadLanguage(), mLangFile, and mLocale.
Referenced by MainWindow().
Field Documentation
QString MainWindow::mAboutText [private]
Definition at line 319 of file mainwindow.h.
Referenced by about(), and retranslateUi().
QString MainWindow::mAboutTitle [private]
Current locale for double -> string.
Definition at line 318 of file mainwindow.h.
Referenced by about(), and retranslateUi().
QApplication* MainWindow::mApp [private]
Reference to the parent application.
Definition at line 303 of file mainwindow.h.
Referenced by copyResultTableSelection(), and MainWindow().
FormulaCompleter* MainWindow::mCompleter [private]
Formula piecewise completion feature.
Definition at line 304 of file mainwindow.h.
Referenced by MainWindow().
DataVisualizer MainWindow::mDataVisualizer [private]
Visualizes selected characteristics of all known chemical elements.
Definition at line 328 of file mainwindow.h.
Referenced by MainWindow(), and retranslateUi().
ElementDatabase::Ptr MainWindow::mDB [private]
Database of all known chemical elements.
Definition at line 325 of file mainwindow.h.
Referenced by showElementData().
QMenu* MainWindow::menuFile [private]
Menubar entry file.
Definition at line 299 of file mainwindow.h.
Referenced by addActions(), MainWindow(), and retranslateUi().
QMenu* MainWindow::menuHelp [private]
Menubar entry help.
Definition at line 302 of file mainwindow.h.
Referenced by addActions(), MainWindow(), and retranslateUi().
QMenu* MainWindow::menuLang [private]
Menubar entry language.
Definition at line 301 of file mainwindow.h.
Referenced by addActions(), MainWindow(), and retranslateUi().
QMenu* MainWindow::menuTools [private]
Menubar entry tools.
Definition at line 300 of file mainwindow.h.
Referenced by addActions(), MainWindow(), and retranslateUi().
QList<FormEntry> MainWindow::mFormEntries [private]
List of all user input fields to process.
Definition at line 344 of file mainwindow.h.
Referenced by MainWindow(), resetInput(), resultAddInput(), saveInitialInput(), and saveInput().
QPalette MainWindow::mFormulaDefaultPalette [private]
To restore the original color of the input formula text.
Definition at line 308 of file mainwindow.h.
Referenced by doCalc(), and MainWindow().
InputData MainWindow::mInputData [private]
Stores input data and calculates compound characteristics.
Definition at line 322 of file mainwindow.h.
Referenced by addAlias(), doCalc(), resetInput(), resultAddData(), resultAddInput(), saveInitialInput(), saveInput(), and setFormattedFormula().
LangActionList MainWindow::mLangActionList [private]
Actions for switching to a certain available language.
Definition at line 311 of file mainwindow.h.
Referenced by updateLangActions().
QString MainWindow::mLangFile [private]
Definition at line 315 of file mainwindow.h.
Referenced by loadLanguage(), and useSystemLocaleTriggered().
QDir MainWindow::mLangPath [private]
Directory path to search for translations.
Definition at line 314 of file mainwindow.h.
Referenced by loadLanguage(), MainWindow(), selectDefaultLang(), and updateLangActions().
QLocale MainWindow::mLocale [private]
Currently loaded language file.
Definition at line 316 of file mainwindow.h.
Referenced by qstringFromDouble(), and useSystemLocaleTriggered().
QStandardItemModel MainWindow::mModel [private]
Backend model for the tabular result widget.
Todo:
Check if InputData could be used as QAbstractItemModel.
Definition at line 332 of file mainwindow.h.
Referenced by clearResultTable(), copyResultTableSelection(), fillResultTable(), MainWindow(), resultAddData(), resultAddInput(), and showElementData().
QTranslator MainWindow::mTranslator [private]
Translates all GUI texts.
Definition at line 305 of file mainwindow.h.
Referenced by loadLanguage(), and MainWindow().
The documentation for this class was generated from the following files:
mainwindow.h
mainwindow.cpp