qSLDcalc: FormulaCompleter Class Reference
FormulaCompleter Class Reference
Chemical element completion during formula input.
#include <formulacompleter.h>
Public Member Functions
FormulaCompleter (const ElementDatabase &db, QLineEdit *ntr, QPushButton *btn)
Constructs this Completer.
Private Slots
void complete (const QString &text)
Calls the QCompleter::complete(const QRect &) slot.
void activated (const QString &text)
Connects to the QCompleter::activated(const QString &) signal.
void highlighted (const QString &text)
Connects to the QCompleter::highlighted(const QString &) signal.
Private Attributes
QCompleter * mCompleter
Does the completion job.
QLineEdit * mLineEdit
Widget to enable completion for.
QPushButton * mBtn
Button with interfering connection.
QString mToken
Current token for completion.
QString mCurText
Current text in mLineEdit.
int mTokenStart
Start of current token in QLineEdit text.
int mTokenEnd
End of current token in QLineEdit text.
Detailed Description
Chemical element completion during formula input.
It does some calculations and string processing to enable completion for single tokens enclosed by whitespace. The default is to just complete the while line of a QTextEdit. But we want to complete single Tokens within that line.
See also:
complete()
Definition at line 42 of file formulacompleter.h.
Constructor & Destructor Documentation
FormulaCompleter::FormulaCompleter (const ElementDatabase & db, QLineEdit * ntr, QPushButton * btn)
Constructs this Completer.
Parameters:
[in] db An ElementDatabase which provides a list of possible tokens to complete (in this case, chemical element names). Calls ElementDatabase::getSymbolList().
[in,out] ntr A QLineEdit which gets this completion.
[in,out] btn A QPushButton which is to the QLineEdit::returnPressed() signal connected, if any.
Definition at line 32 of file formulacompleter.cpp.
References activated(), complete(), ElementDatabase::getSymbolList(), highlighted(), and mCompleter.
Member Function Documentation
void FormulaCompleter::activated (const QString & text) [private, slot]
Connects to the QCompleter::activated(const QString &) signal.
It connects the previously disconnected QLineEdit::returnPressed() signal to its original receiver (the supplied QPushButton).
Parameters:
[in] text The finally selected item from the popup dropdown list.
Definition at line 52 of file formulacompleter.cpp.
References mBtn, and mLineEdit.
Referenced by FormulaCompleter().
void FormulaCompleter::complete (const QString & text) [private, slot]
Calls the QCompleter::complete(const QRect &) slot.
Calculations for piecewise completion of the supplied string occurs here. See above.
Parameters:
[in] text The text of the QLineEdit.
Definition at line 73 of file formulacompleter.cpp.
References mCompleter, mCurText, mLineEdit, mToken, mTokenEnd, and mTokenStart.
Referenced by FormulaCompleter().
void FormulaCompleter::highlighted (const QString & text) [private, slot]
Connects to the QCompleter::highlighted(const QString &) signal.
It replaces the current token with the selected one within the QLineEdit text. If the QPushButton is set, it temporarily disconnects the QLineEdit::returnPressed() signal from it when an item is selected. This avoids interference with the original receiver of this signal.
Parameters:
[in] text Selected item in the popup dropdown list.
Definition at line 60 of file formulacompleter.cpp.
References mBtn, mCurText, mLineEdit, mTokenEnd, and mTokenStart.
Referenced by FormulaCompleter().
Field Documentation
QPushButton* FormulaCompleter::mBtn [private]
Button with interfering connection.
Definition at line 81 of file formulacompleter.h.
Referenced by activated(), and highlighted().
QCompleter* FormulaCompleter::mCompleter [private]
Does the completion job.
Definition at line 79 of file formulacompleter.h.
Referenced by complete(), and FormulaCompleter().
QString FormulaCompleter::mCurText [private]
Current text in mLineEdit.
Definition at line 83 of file formulacompleter.h.
Referenced by complete(), and highlighted().
QLineEdit* FormulaCompleter::mLineEdit [private]
Widget to enable completion for.
Definition at line 80 of file formulacompleter.h.
Referenced by activated(), complete(), and highlighted().
QString FormulaCompleter::mToken [private]
Current token for completion.
Definition at line 82 of file formulacompleter.h.
Referenced by complete().
int FormulaCompleter::mTokenEnd [private]
End of current token in QLineEdit text.
Definition at line 85 of file formulacompleter.h.
Referenced by complete(), and highlighted().
int FormulaCompleter::mTokenStart [private]
Start of current token in QLineEdit text.
Definition at line 84 of file formulacompleter.h.
Referenced by complete(), and highlighted().
The documentation for this class was generated from the following files:
formulacompleter.h
formulacompleter.cpp