qSLDcalc: ElementDatabase Class Reference
ElementDatabase Class Reference
Contains all chemical elements currently known by this program.
#include <elementdatabase.h>
Public Types
typedef QPointer< ElementDatabase > Ptr
Guarded pointer to this database.
typedef QString KeyType
Key data type by which all elements are identified within the database.
typedef ElementHash::const_iterator Iterator
An iterator over the whole element database.
Public Member Functions
~ElementDatabase ()
Cleanup, frees internal data.
void addFromFile (const QString &fn)
Adds all elements within a single file to the database.
void addFromDirectory (const QString &path)
Adds all elements from all XML files within the specified directory to the database.
Element::Ptr getElement (const KeyType &key)
Retrieves an element dataset with the specified key from the database.
Element::Ptr getElement (const cfp::ChemicalElementInterface &e)
Retrieves an element dataset for the specified chemical element signature from the database.
QStringList getSymbolList () const
Generates a symbol list of all available elements in the database.
Iterator begin () const
Returns an iterator to begin with when iterating over all elements.
Iterator end () const
Returns an iterator to end with when interating over all elements.
void addAlias (const KeyType &key, const cfp::Compound &compound)
Adds an alias to the database.
const cfp::Compound getAlias (const KeyType &key) const
Retrieves a compound by the specified alias from the database.
const cfp::Compound getAlias (const cfp::ChemicalElementInterface &e) const
Retrieves a compound by the specified chemical element signature from the database.
Static Public Member Functions
static const KeyType makeKey (const cfp::ChemicalElementInterface &e)
Generates a key based on the given chemical element signature for retrieval of database elements.
Private Types
typedef QHash< KeyType,
Element::Ptr > ElementHash
The hash table type used for chemical elements.
typedef QHash< KeyType,
cfp::Compound > AliasHash
The hash table type used for aliases of compunds.
Private Attributes
ElementHash mElementHash
Hash table for chemical element datasets.
AliasHash mAliasHash
Hash table for compound aliases.
Friends
std::ostream & operator<< (std::ostream &o, const ElementDatabase &db)
Outputs the string representation of an element database to an output stream.
Detailed Description
Contains all chemical elements currently known by this program.
It stores the alias names for element compounds separately because an ordinary database element can not store the associated cfp::Compound (for aliases).
The element datasets are not sorted in any way but can be retrieved in constant time complexity.
Todo:
Combine single chemical elements and aliases (cfp::Compound) into a single data type. Pro: aliases could be easily visualized in the same way as regular elements. Con: Additional (unused) data fields for ordinary chemical elements (minor) and all the properties of a single element have to be calculated for compounds too: At alias creation time or at access time (major, regarding visualization).
Todo:
Add a preconfigured list of aliases, similar to http://www.chemcalc.org .
Todo:
Save user-defined aliases to a file in the users home-directory to restore them after restart of the application.
Definition at line 65 of file elementdatabase.h.
Member Typedef Documentation
typedef QHash<KeyType, cfp::Compound> ElementDatabase::AliasHash [private]
The hash table type used for aliases of compunds.
Definition at line 78 of file elementdatabase.h.
typedef QHash<KeyType, Element::Ptr> ElementDatabase::ElementHash [private]
The hash table type used for chemical elements.
Definition at line 76 of file elementdatabase.h.
typedef ElementHash::const_iterator ElementDatabase::Iterator
An iterator over the whole element database.
Definition at line 81 of file elementdatabase.h.
typedef QString ElementDatabase::KeyType
Key data type by which all elements are identified within the database.
The chemical element symbol name. Isotopes have the nucleon number prepended.
Definition at line 73 of file elementdatabase.h.
typedef QPointer<ElementDatabase> ElementDatabase::Ptr
Guarded pointer to this database.
Definition at line 69 of file elementdatabase.h.
Constructor & Destructor Documentation
ElementDatabase::~ElementDatabase ()
Cleanup, frees internal data.
Definition at line 32 of file elementdatabase.cpp.
References mElementHash.
Member Function Documentation
void ElementDatabase::addAlias (const KeyType & key, const cfp::Compound & compound)
Adds an alias to the database.
Parameters:
[in] key The alias name.
[in] compound The compound which is identified by the alias.
Definition at line 120 of file elementdatabase.cpp.
References mAliasHash.
void ElementDatabase::addFromDirectory (const QString & path)
Adds all elements from all XML files within the specified directory to the database.
Parameters:
[in] path Full path to a directory which contains XML files with chemical element definitions.
Definition at line 50 of file elementdatabase.cpp.
References addFromFile().
Referenced by main().
void ElementDatabase::addFromFile (const QString & fn)
Adds all elements within a single file to the database.
This file must follow the syntax defined and used by XmlParser.
Parameters:
[in] fn Filename of the XML file containing chemical element definitions.
Definition at line 40 of file elementdatabase.cpp.
References makeKey(), mElementHash, and XmlParser::read().
Referenced by addFromDirectory().
ElementDatabase::Iterator ElementDatabase::begin () const
Returns an iterator to begin with when iterating over all elements.
Definition at line 108 of file elementdatabase.cpp.
References mElementHash.
ElementDatabase::Iterator ElementDatabase::end () const
Returns an iterator to end with when interating over all elements.
Definition at line 114 of file elementdatabase.cpp.
References mElementHash.
const cfp::Compound ElementDatabase::getAlias (const cfp::ChemicalElementInterface & e) const
Retrieves a compound by the specified chemical element signature from the database.
Definition at line 132 of file elementdatabase.cpp.
References makeKey(), and mAliasHash.
const cfp::Compound ElementDatabase::getAlias (const KeyType & key) const
Retrieves a compound by the specified alias from the database.
Definition at line 126 of file elementdatabase.cpp.
References mAliasHash.
Element::Ptr ElementDatabase::getElement (const cfp::ChemicalElementInterface & e)
Retrieves an element dataset for the specified chemical element signature from the database.
Definition at line 81 of file elementdatabase.cpp.
References makeKey(), and mElementHash.
Element::Ptr ElementDatabase::getElement (const KeyType & key)
Retrieves an element dataset with the specified key from the database.
Definition at line 75 of file elementdatabase.cpp.
References mElementHash.
QStringList ElementDatabase::getSymbolList () const
Generates a symbol list of all available elements in the database.
Returns:
A list of all available symbols according to KeyType.
Definition at line 87 of file elementdatabase.cpp.
References mElementHash.
Referenced by FormulaCompleter::FormulaCompleter(), and operator<<().
const ElementDatabase::KeyType ElementDatabase::makeKey (const cfp::ChemicalElementInterface & e) [static]
Generates a key based on the given chemical element signature for retrieval of database elements.
Parameters:
[in] e Chemical element signature to generate a key for.
Definition at line 68 of file elementdatabase.cpp.
Referenced by addFromFile(), getAlias(), getElement(), and DataVisualizer::getLinkText().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const ElementDatabase & db) [friend]
Outputs the string representation of an element database to an output stream.
Parameters:
[out] o Stream to write to.
[in] db Element database to stringify.
Definition at line 98 of file elementdatabase.cpp.
Field Documentation
AliasHash ElementDatabase::mAliasHash [private]
Hash table for compound aliases.
Definition at line 137 of file elementdatabase.h.
Referenced by addAlias(), and getAlias().
ElementHash ElementDatabase::mElementHash [private]
Hash table for chemical element datasets.
Definition at line 136 of file elementdatabase.h.
Referenced by addFromFile(), begin(), end(), getElement(), getSymbolList(), operator<<(), and ~ElementDatabase().
The documentation for this class was generated from the following files:
elementdatabase.h
elementdatabase.cpp