qSLDcalc: element.cpp File Reference
element.cpp File Reference
#include "element.h"
Functions
std::ostream & operator<< (std::ostream &o, const Element &e)
Feed the string representation of a database element to a std::stream.
Function Documentation
std::ostream& operator<< (std::ostream & o, const Element & e)
Feed the string representation of a database element to a std::stream.
Definition at line 211 of file element.cpp.
References Element::beginConst(), Element::endConst(), and Element::xrayCoefficients().