qSLDcalc: element.h File Reference
element.h File Reference
#include <complex>
#include <vector>
#include <map>
#include <iostream>
#include <QPointer>
#include <cfp/cfp.h>
#include <boost/variant.hpp>
Data Structures
class Element
A real-world chemical element.
Namespaces
namespace std
STL namespace.
Typedefs
typedef std::complex< double > complex
Complex numbers in floating point representation.
typedef std::pair< double, double > DoublePair
A tuple of floating point numbers.
typedef std::map< double,
DoublePair > MapTriple
A Map of floating point numbers used to store the Xray scattering factors indexed by their energy.
Functions
std::ostream & operator<< (std::ostream &o, const Element &e)
Feed the string representation of a database element to a std::stream.
bool std::operator< (const ::complex &a, const ::complex &b)
Comparison of complex numbers by length (Euclidian Norm).
Typedef Documentation
typedef std::complex<double> complex
Complex numbers in floating point representation.
Definition at line 39 of file element.h.
typedef std::pair<double, double> DoublePair
A tuple of floating point numbers.
Definition at line 42 of file element.h.
typedef std::map<double, DoublePair> MapTriple
A Map of floating point numbers used to store the Xray scattering factors indexed by their energy.
See also:
Element::xrayCoefficients()
Definition at line 47 of file element.h.
Function Documentation
std::ostream& operator<< (std::ostream & o, const Element & e)
Feed the string representation of a database element to a std::stream.
Definition at line 211 of file element.cpp.
References Element::beginConst(), Element::endConst(), and Element::xrayCoefficients().