qSLDcalc: inputdata.cpp File Reference
inputdata.cpp File Reference
#include <numeric>
#include <functional>
#include "utils.h"
#include "inputdata.h"
Functions
void addComplex2Map (QVariantMap &map, const char *key, complex c)
double interpolate (double x1, double y1, double x2, double y2, double x3)
complex sldXray (double electrons, double fp, double fpp, double vol)
Function Documentation
void addComplex2Map (QVariantMap & map, const char * key, complex c)
Definition at line 112 of file inputdata.cpp.
Referenced by InputData::calcNSL(), and InputData::calcXrayEnergies().
double interpolate (double x1, double y1, double x2, double y2, double x3)
Definition at line 211 of file inputdata.cpp.
Referenced by InputData::calcXrayCoefficients().
complex sldXray (double electrons, double fp, double fpp, double vol)
Definition at line 217 of file inputdata.cpp.
References electronRadius().
Referenced by InputData::calcXrayEnergies().